# Generated by Django 5.2 on 2025-05-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capital_city', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('area', models.FloatField()),
                ('official_languages', models.CharField(max_length=255)),
                ('continent', models.CharField(max_length=255)),
                ('main_cities', models.CharField(max_length=255)),
                ('climate', models.CharField(max_length=255)),
                ('gdp', models.FloatField()),
                ('currency', models.CharField(max_length=255)),
            ],
        ),
    ]
